### ISSUE TITLE
data saves but allows for duplicates. Err.Catch() {

### ISSUE THREAD

**Issue by frankcollins3** [frankcollins3/mine-nugget-ts#14]
Unique constraint failed on the fields: (`usersId`,`strainsId`)
    at RequestHandler.handleRequestError (/Users/medium/Desktop/mine-nugget-ts/node_modules/@prisma/client/runtime/index.js:34310:13)
    at RequestHandler.request (/Users/medium/Desktop/mine-nugget-ts/node_modules/@prisma/client/runtime/index.js:34293:12)
    at async PrismaClient._request (/Users/medium/Desktop/mine-nugget-ts/node_modules/@prisma/client/runtime/index.js:35273:16)
    at async relationalStrainToUser (webpack-internal:///(api)/./pages/api/strains/postuserstrains.ts:46:22)
    at async eval (webpack-internal:///(api)/./pages/api/strains/postuserstrains.ts:225:32) {
  code: 'P2002',
  clientVersion: '4.6.1',
  meta: { target: [ 'usersId', 'strainsId' ] }
}

          strains: {                            // strains here represents [prisma.UsersOnStrains] not [prisma.strains]
                        createMany: {
                               data: [{ strainsId: strainsId}],   
                        },

i already did a test of: 

data: [{ strainId: strainsId + 1}]  after creating the strain.
1) you can run this once after you update a strain. then it will save the next strain in the index. 
2) then you will violate duplicate/ [prisma:uniqueId] error seen above

**Comment by frankcollins3** [comment]
ERROR:  update or delete on table "users" violates foreign key constraint "UsersOnStrains_usersId_fkey" on table "UsersOnStrains"
DETAIL:  Key (id)=(4) is still referenced from table "UsersOnStrains".
mine_nugget_dev=# DELETE FROM "UsersOnStrains" where "usersId" > 0;
DELETE 1
mine_nugget_dev=# DELETE FROM users WHERE id > 0;
DELETE 5
mine_nugget_dev=#

deleting table data for Users and UsersOnStrains.
helps to know how intertwined they become and how it relates to the commands that can be used on either table

**Comment by frankcollins3** [comment]
(good to see)
running commands with no data: 
  
meta: {
    cause: "No 'users' record (needed to inline the relation on 'UsersOnStrains' record) was found for a nested createMany on relation 'UsersOnStrainsTousers'."
  }
}

**Comment by frankcollins3** [comment]
_code is still trying to create data instead of skipping duplicate. That has to be done in a .createMany()_
        
data: {
                                       strains: {                            
                                createMany: {
                                       data: [{ strainsId: strainsId }],   
                                    },
                                },
                                **skipDuplicates: true,** 
                            },

**Comment by frankcollins3** [comment]
![Screen Shot 2022-12-12 at 12 00 41 PM](https://user-images.githubusercontent.com/73137934/207107332-375769db-7544-470a-b65d-6394275e403b.png)

skip duplicates only working for createMany and Many-To-Many relationships not working for createMany... 

tangled a little

**Comment by frankcollins3** [comment]
const checkstrain = await prisma.users.findFirst({
                    where: {
                      id: user 
                    },
                    include: {
                        strains: true
                    }
                }).then(async(founduser) => {
                    let userstrains = founduser.strains
                    let values = await ReturnEndpoints(founduser.strains, 'values')
                    console.log('values')
                    console.log(values.strainId)
                    return founduser
                })

relational query. returns the table.UsersOnStrains of the table.user from the **association described as:**

model users {
  id        Int      @id @default(autoincrement())
  username  String?  @db.VarChar(255)
  password  String?  @db.VarChar(255)
  age       Int?
  email     String?  @db.VarChar(255)
  **strains   UsersOnStrains[]**  
}

**Comment by frankcollins3** [comment]
error blocks and filtering with user.strain first. It does not save to the database twice even if you try to save the strain twice.
