### ISSUE TITLE
hydration issue: styled-components, SWC/.babelrc/compileroptions...

### ISSUE THREAD

**Issue by frankcollins3** [frankcollins3/mine-nugget-ts#4]
.babelrc
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }]]
}

did a mini-dive on next.js SWC (speedy web compiler) and why .babelrc overrode all of my apps config settings.

next-dev.js?3515:20 Warning: Prop `className` did not match. Server: "sc-gswNZR hToHwn" Client: "sc-bcXHqe ihfkED"
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at StrainDisplay (webpack-internal:///./components/StrainDisplay.tsx:23:33)
    at div
    at Strain (webpack-internal:///./pages/strain.tsx:28:94)
    at App (webpack-internal:///./pages/_app.tsx:24:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3325)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6707)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error

**Comment by frankcollins3** [comment]
restart server delete .babelrc

app is alive again but the error, and so solution-sourcing persists

**Comment by frankcollins3** [comment]
reset next.config 
started commenting out whole components and temporarily-deleting functionality to isolate problem.

Added fragments and re-wrote props. issue went away.

this problem of SSR & behind-scenes-functionality / DOM & render-tree functionality being out of sync 
can be made worse by jquery and doing XML data or DOM and keeping it away from react-state.

issue closed successfully for now. nice lessons learned on next.js config & {hydration: server|dom}

**Comment by frankcollins3** [comment]
styled-components.browser.esm.js?eee5:1 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.

See https://s-c.sh/2BAXzed for more info.
